Repository netguru-code-college/vol2-alpha, pull requests merged in 2018-02, with the labels that each got.

#3 Create PULL_REQUEST_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#4 Create model Technology
  app/models/technology.rb
  db/migrate/20180223083933_create_technologies.rb
  test/fixtures/technologies.yml
  test/models/technology_test.rb
Labels: bug, duplicate, enhancement, good first issue, question

#10 Add the relations between User and Opinion classes
  app/models/opinion.rb
  app/models/user.rb
  app/models/users_opinion.rb
  db/migrate/20180223123541_create_users_opinions.rb
  db/migrate/20180223125127_add_user_id_and_opinion_id_to_levels.rb
  db/schema.rb
  spec/models/users_opinion_spec.rb
Labels: 🍝 Spaghetti

#11 Create user language relationship
  app/models/language.rb
  app/models/speaker.rb
  app/models/user.rb
  db/migrate/20180223122859_create_speakers.rb
  db/schema.rb
Labels: can't fix won't fix

#15 Frontend
  app/assets/images/favicon.ico
  app/assets/stylesheets/application.scss
  app/views/layouts/_alerts.html.haml
  app/views/layouts/_footer.html.haml
  app/views/layouts/_navbar.html.haml
  app/views/layouts/application.html.erb
  app/views/layouts/application.html.haml
  app/views/layouts/mailer.html.erb
  app/views/layouts/mailer.html.haml
  app/views/layouts/mailer.text.erb
  app/views/layouts/mailer.text.haml
  app/views/users/index.html.haml
  app/views/users/search.html.haml
  public/favicon.ico
Labels: 🍝 Spaghetti

#20 Add an end
  app/controllers/users_controller.rb
Labels: Going to selfmerge this whether you like it or not, High Priority

#22 Travis, my love
  .travis.yml
  README.md
  spec/models/users_opinion_spec.rb
Labels: Going to selfmerge this whether you like it or not

#27 Devise stuffs
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/models/user.rb
  app/views/devise/confirmations/new.html.haml
  app/views/devise/mailer/confirmation_instructions.html.haml
  app/views/devise/mailer/email_changed.html.haml
  app/views/devise/mailer/password_change.html.haml
  app/views/devise/mailer/reset_password_instructions.html.haml
  app/views/devise/mailer/unlock_instructions.html.haml
  app/views/devise/passwords/edit.html.haml
  app/views/devise/passwords/new.html.haml
  app/views/devise/registrations/edit.html.haml
  app/views/devise/registrations/new.html.haml
  app/views/devise/sessions/new.html.haml
  app/views/devise/shared/_links.html.haml
  app/views/devise/unlocks/new.html.haml
Labels: 🍝 Spaghetti
